# Generated by Django 5.1.1 on 2024-10-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='email',
            field=models.CharField(default='-', max_length=50, verbose_name='Email'),
        ),
    ]
