# Generated by Django 5.1.1 on 2024-10-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0002_players_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('score', models.IntegerField(verbose_name='Очки')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dino.levels'),
        ),
    ]
