# Generated by Django 5.1.1 on 2024-10-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0003_levels_players_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerslevel', to='Dino.levels', verbose_name='Уровень'),
        ),
    ]
